FROM node:20-alpine AS build

ARG VITE_AUTH0_DOMAIN
ARG VITE_AUTH0_CLIENT_ID
ARG VITE_BACKEND_URL
ARG VITE_FRONTEND_URL
ARG VITE_SNIPPETS_SERVICE_URL
ARG VITE_RUNNER_SERVICE_URL

ENV VITE_AUTH0_DOMAIN=${VITE_AUTH0_DOMAIN}
ENV VITE_AUTH0_CLIENT_ID=${VITE_AUTH0_CLIENT_ID}
ENV VITE_BACKEND_URL=${VITE_BACKEND_URL}
ENV VITE_FRONTEND_URL=${VITE_FRONTEND_URL}
ENV VITE_SNIPPETS_SERVICE_URL=${VITE_SNIPPETS_SERVICE_URL}
ENV VITE_RUNNER_SERVICE_URL=${VITE_RUNNER_SERVICE_URL}

WORKDIR /app
COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# Etapa de runtime
FROM nginx:alpine

# Si más adelante querés SPA full, podés agregar un nginx.conf custom
# COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
