export const FRONTEND_URL = process?.env?.FRONTEND_URL ?? "https://ingsis25.duckdns.org"
export const BACKEND_URL = process?.env?.BACKEND_URL ?? "http://localhost:8001/api"
export const AUTH0_USERNAME = process?.env?.AUTH0_USERNAME ?? "test@gmail.com"
export const AUTH0_PASSWORD = process?.env?.AUTH0_PASSWORD ?? "Ingenieria2025!"
export const SNIPPETS_SERVICE_URL = process?.env?.VITE_SNIPPETS_SERVICE_URL ?? "http://localhost:8001"
export const RUNNER_SERVICE_URL = process?.env?.VITE_RUNNER_SERVICE_URL ?? "http://localhost:8000"
export const VITE_AUTH0_AUDIENCE =  process?.env?.VITE_AUTH0_AUDIENCE ?? "https://snippet-searcher.api"
