export const FRONTEND_URL = import.meta.env.VITE_FRONTEND_URL ?? "http://localhost:5173"
export const BACKEND_URL = process?.env?.BACKEND_URL ?? "http://localhost:8001/api"
export const AUTH0_USERNAME = process?.env?.AUTH0_USERNAME ?? ""
export const AUTH0_PASSWORD = process?.env?.AUTH0_PASSWORD ?? ""
export const SNIPPETS_SERVICE_URL = import.meta.env.VITE_SNIPPETS_SERVICE_URL ?? "http://localhost:8001"
export const RUNNER_SERVICE_URL = import.meta.env.VITE_RUNNER_SERVICE_URL ?? "http://localhost:8000"
export const VITE_AUTH0_AUDIENCE =  import.meta.env.VITE_AUTH0_AUDIENCE ?? "https://snippet-searcher.api"
